on:
  schedule:
    - cron: 0 12 */7 * *
  push:
    paths:
      - '.github/workflows/ubuntu.yml'
      - 'linux/ubuntu/**'
    branches:
      - main
    tags:
      - "*"
  pull_request:
    paths:
      - '.github/workflows/ubuntu.yml'
      - 'linux/ubuntu/**'
  workflow_dispatch:
jobs:
  main:
    name: Build base ${{ matrix.platform }} ${{ matrix.tag }}
    runs-on: ubuntu-latest
    env:
      PLATFORMS: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        tag:
          - '23.10'
        assembly:
          - default
    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/lipg/runner
          tags: |
            type=ref,event=branch,prefix=ubuntu-
            type=ref,event=tag,prefix=ubuntu-
            type=ref,event=pr,prefix=ubuntu-
            type=sha,prefix=ubuntu-
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='Asia/Shshanghai'}},prefix=ubuntu-
            type=raw,value=latest,enable={{is_default_branch}},prefix=ubuntu-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ steps.platforms.outputs.matrix }}
          context: linux/ubuntu/
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            FROM_IMAGE=ubuntu
            FROM_TAG=${{ matrix.tag }}
            ASSEMBLY=${{ matrix.assembly }}